language: swift
osx_image: xcode9.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=LJNetwork.xcworkspace
  - IOS_FRAMEWORK_SCHEME="LJNetwork"
  - EXAMPLE_SCHEME="LJNetwork"

xcode_workspace: $WORKSPACE
xcode_schemes: $EXAMPLE_SCHEME

profile: Podfile

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update  
